# Generated by Django 3.0 on 2019-08-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffnum', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=32)),
                ('mailbox', models.EmailField(max_length=128)),
                ('hiredate', models.DateField()),
                ('staffphone', models.CharField(max_length=20)),
                ('stafftitle', models.CharField(max_length=20)),
                ('leader', models.CharField(max_length=32)),
            ],
        ),
    ]
